import { getModelForClass } from '@typegoose/typegoose';
import { Level } from '../features/level/model';
import { Department } from '../features/department/model';
import { LeaveType } from '../features/leaveType/model';
import { Position } from '../features/position/model';
import { LeaveRequest } from '../features/leaveRequest/model';
import { Medias } from '../features/medias/schema';
import { VoucherAccount } from '../features/voucherAccount/schema';
import { Grade } from '../features/grade/schema';
import { InvoiceEmail } from '../features/invoiceEmail/schema';
import { PerformanceReview } from '../features/performanceReview/schema';
import { Performance } from '../features/performance/schema';
import { InvoiceCode } from '../features/invoiceCode/schema';
import { Announcement } from '../features/announcement/schema';
import { VoucherCompanies } from '../features/voucherCompanies/schema';
import { Voucher } from '../features/voucher/schema';
import { InvoiceAccount } from '../features/invoiceAccount/schema';
import { InvoiceTag } from '../features/invoiceTag/schema';
import { InvoiceContact } from '../features/invoiceContact/schema';
import { InvoiceItem } from '../features/invoiceItem/schema';
import { Invoice } from '../features/invoice/schema';
import { RequestForm } from '../features/requestForm/schema';
import { Request } from '../features/request/schema';
import { JobApplication } from '../features/jobApplication/schema';
import { FormResponse } from '../features/formResponse/schema';
import { FormQuestion } from '../features/formQuestion/schema';
import { Form } from '../features/form/schema';
import { Job } from '../features/job/schema';
import { Resignation } from '../features/resignation/schema';
import { File } from '../features/file/schema';
import { Company } from '../features/company/model';

export const VoucherAccountModel = getModelForClass(VoucherAccount);
export const GradeModel = getModelForClass(Grade);
export const InvoiceEmailModel = getModelForClass(InvoiceEmail);
export const PerformanceReviewModel = getModelForClass(PerformanceReview);
export const PerformanceModel = getModelForClass(Performance);
export const InvoiceCodeModel = getModelForClass(InvoiceCode);
export const AnnouncementModel = getModelForClass(Announcement);
export const VoucherCompaniesModel = getModelForClass(VoucherCompanies);
export const VoucherModel = getModelForClass(Voucher);
export const MediasModel = getModelForClass(Medias);
export const InvoiceAccountModel = getModelForClass(InvoiceAccount);
export const InvoiceTagModel = getModelForClass(InvoiceTag);
export const InvoiceContactModel = getModelForClass(InvoiceContact);
export const InvoiceItemModel = getModelForClass(InvoiceItem);
export const InvoiceModel = getModelForClass(Invoice);
export const RequestFormModel = getModelForClass(RequestForm);
export const RequestModel = getModelForClass(Request);
export const JobApplicationModel = getModelForClass(JobApplication);
export const FormResponseModel = getModelForClass(FormResponse);
export const FormQuestionModel = getModelForClass(FormQuestion);
export const FormModel = getModelForClass(Form);
export const JobModel = getModelForClass(Job);
export const ResignationModel = getModelForClass(Resignation);
export const FileModel = getModelForClass(File);
export const LevelModel = getModelForClass(Level);
export const DepartmentModel = getModelForClass(Department);
export const LeaveTypeModel = getModelForClass(LeaveType);
export const PositionModel = getModelForClass(Position);
export const LeaveRequestModel = getModelForClass(LeaveRequest);
export const CompanyModel = getModelForClass(Company);
